name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  abi-free:
    name: ABI compilers (free)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Check free compiler ABIs
        run: >-
          nix build --print-build-logs
          .#checks.x86_64-linux.abi-generic-le
          .#checks.x86_64-linux.abi-arm-aapcs32-le
          .#checks.x86_64-linux.abi-riscv-ilp32-le
          .#checks.x86_64-linux.abi-generic-be

  abi-ti-c28x:
    name: ABI compiler (TI C28x)
    runs-on: ubuntu-latest
    steps:
      - name: Permit nested FHS installer sandbox
        run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
      - name: Checkout source code
        uses: actions/checkout@v5
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - name: Check TI C28x EABI
        run: nix build --print-build-logs .#checks.x86_64-linux.abi-ti-c28x-eabi

  rust-style:
    name: Rust style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Check workspace
        run: cargo check --workspace --all-features --locked

      - name: Check clippy
        run: cargo clippy --workspace --all-targets --all-features --locked

  rust:
    name: Rust ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Check workspace
        run: cargo check --workspace --all-features --locked

      - name: Test workspace
        run: cargo test --workspace --locked
